# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Project metadata – fill in the placeholders with your info
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[project]
name = "geeode"
version = "1.0.4"
description = "A Google Earth Engine package for Optimization via Differential Evolution"
readme = "README.md"
license = {text = "BSD-3-Clause"}
authors = [
    {name = "Devin Routh", email = "devin.routh@uzh.ch"},
    {name = "Claudia Röösli", email = "claudia.roeoesli@geo.uzh.ch"}
]

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Python Version
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
requires-python = ">=3.11,<4.0"

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Runtime dependencies
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
dependencies = [
    "earthengine-api==1.7.43",
    "pandas>=2.0,<3.0"
]

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Optional / development dependencies
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[project.optional-dependencies]

test = [
    "pytest>=9.0.0"
]

docs = [
    "mkdocs>=1.6.1,<2.0",
    "mkdocs-material>=9.7.0,<10.0",
    "mkdocstrings>=0.30.1,<1.0",
    "mkdocstrings-python>=1.19.0,<2.0",
]

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Build system – keep the default setuptools configuration
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Parameterize setuptools
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.package-data]
include = [
    "paper/**",
    "tests/**"
]

